export const getProducto_ActionType = {
    GET_PRODUCTO_REQUEST:'GET_PRODUCTO_REQUEST',
    GET_PRODUCTO_SUCCESS:'GET_PRODUCTO_SUCCESS',
    GET_PRODUCTO_FAILURE:'GET_PRODUCTO_FAILURE'
 }

export const postProducto_ActionType = {
    POST_PRODUCTO_REQUEST:'POST_PRODUCTO_REQUEST',
    POST_PRODUCTO_SUCCESS:'POST_PRODUCTO_SUCCESS',
    POST_PRODUCTO_FAILURE:'POST_PRODUCTO_FAILURE'
 }

 export const putProducto_ActionType = {
    PUT_PRODUCTO_REQUEST:'PUT_PRODUCTO_REQUEST',
    PUT_PRODUCTO_SUCCESS:'PUT_PRODUCTO_SUCCESS',
    PUT_PRODUCTO_FAILURE:'PUT_PRODUCTO_FAILURE'
 }

 export const deleteProducto_ActionType = {
    DELETE_PRODUCTO_REQUEST:'DELETE_PRODUCTO_REQUEST',
    DELETE_PRODUCTO_SUCCESS:'DELETE_PRODUCTO_SUCCESS',
    DELETE_PRODUCTO_FAILURE:'DELETE_PRODUCTO_FAILURE'
 }

 export const menu_ActionType={

    PRODUCTO_MENU_INVENTARIO:'PRODUCTO_MENU_INVENTARIO'

 }
  

 export default {getProducto_ActionType, postProducto_ActionType, deleteProducto_ActionType, putProducto_ActionType}