export const getVolante_ActionType = {
    GET_VOLANTE_REQUEST:'GET_VOLANTE_REQUEST',
    GET_VOLANTE_SUCCESS:'GET_VOLANTE_SUCCESS',
    GET_VOLANTE_FAILURE:'GET_VOLANTE_FAILURE'
 }

export const postVolante_ActionType = {
    POST_VOLANTE_REQUEST:'POST_VOLANTE_REQUEST',
    POST_VOLANTE_SUCCESS:'POST_VOLANTE_SUCCESS',
    POST_VOLANTE_FAILURE:'POST_VOLANTE_FAILURE'
 }

 export const putVolante_ActionType = {
    PUT_VOLANTE_REQUEST:'PUT_VOLANTE_REQUEST',
    PUT_VOLANTE_SUCCESS:'PUT_VOLANTE_SUCCESS',
    PUT_VOLANTE_FAILURE:'PUT_VOLANTE_FAILURE'
 }

 export const deleteVolante_ActionType = {
    DELETE_VOLANTE_REQUEST:'DELETE_VOLANTE_REQUEST',
    DELETE_VOLANTE_SUCCESS:'DELETE_VOLANTE_SUCCESS',
    DELETE_VOLANTE_FAILURE:'DELETE_VOLANTE_FAILURE'
 }
 
 export const productoVolante_ActionType ={
   ADD_PRODUCTO_VOLANTE:"ADD_PRODUCTO_VOLANTE",
   REMOVE_PRODUCTO_VOLANTE:"REMOVE_PRODUCTOVOLANTE",
   REMOVE_ALL_VOLANTE:"REMOVE_ALL_VOLANTE"
}

export const detalleVolante_ActionType={
   VIEW_VOLANTE_DETAIL:"VIEW_VOLANTE_DETAIL"
}
 export default{getVolante_ActionType, postVolante_ActionType, putVolante_ActionType, deleteVolante_ActionType, detalleVolante_ActionType}